/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.UiVariant;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * CfarOffersBannerDisplay
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-02T17:40:08.115903591Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class CfarOffersBannerDisplay {
  public static final String SERIALIZED_NAME_OCCURRED_DATE_TIME = "occurred_date_time";
  @SerializedName(SERIALIZED_NAME_OCCURRED_DATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime occurredDateTime;

  public static final String SERIALIZED_NAME_CFAR_OFFERS_IDS = "cfar_offers_ids";
  @SerializedName(SERIALIZED_NAME_CFAR_OFFERS_IDS)
  @javax.annotation.Nonnull
  private List<String> cfarOffersIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_UI_VARIANT = "ui_variant";
  @SerializedName(SERIALIZED_NAME_UI_VARIANT)
  @javax.annotation.Nonnull
  private UiVariant uiVariant;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public CfarOffersBannerDisplay() {
  }

  public CfarOffersBannerDisplay occurredDateTime(@javax.annotation.Nonnull OffsetDateTime occurredDateTime) {
    this.occurredDateTime = occurredDateTime;
    return this;
  }

  /**
   * A UTC [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) datetime;  the date and time at which an event occurred on a client device
   * @return occurredDateTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getOccurredDateTime() {
    return occurredDateTime;
  }

  public void setOccurredDateTime(@javax.annotation.Nonnull OffsetDateTime occurredDateTime) {
    this.occurredDateTime = occurredDateTime;
  }


  public CfarOffersBannerDisplay cfarOffersIds(@javax.annotation.Nonnull List<String> cfarOffersIds) {
    this.cfarOffersIds = cfarOffersIds;
    return this;
  }

  public CfarOffersBannerDisplay addCfarOffersIdsItem(String cfarOffersIdsItem) {
    if (this.cfarOffersIds == null) {
      this.cfarOffersIds = new ArrayList<>();
    }
    this.cfarOffersIds.add(cfarOffersIdsItem);
    return this;
  }

  /**
   * Get cfarOffersIds
   * @return cfarOffersIds
   */
  @javax.annotation.Nonnull
  public List<String> getCfarOffersIds() {
    return cfarOffersIds;
  }

  public void setCfarOffersIds(@javax.annotation.Nonnull List<String> cfarOffersIds) {
    this.cfarOffersIds = cfarOffersIds;
  }


  public CfarOffersBannerDisplay uiVariant(@javax.annotation.Nonnull UiVariant uiVariant) {
    this.uiVariant = uiVariant;
    return this;
  }

  /**
   * Get uiVariant
   * @return uiVariant
   */
  @javax.annotation.Nonnull
  public UiVariant getUiVariant() {
    return uiVariant;
  }

  public void setUiVariant(@javax.annotation.Nonnull UiVariant uiVariant) {
    this.uiVariant = uiVariant;
  }


  public CfarOffersBannerDisplay type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CfarOffersBannerDisplay cfarOffersBannerDisplay = (CfarOffersBannerDisplay) o;
    return Objects.equals(this.occurredDateTime, cfarOffersBannerDisplay.occurredDateTime) &&
        Objects.equals(this.cfarOffersIds, cfarOffersBannerDisplay.cfarOffersIds) &&
        Objects.equals(this.uiVariant, cfarOffersBannerDisplay.uiVariant) &&
        Objects.equals(this.type, cfarOffersBannerDisplay.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(occurredDateTime, cfarOffersIds, uiVariant, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CfarOffersBannerDisplay {\n");
    sb.append("    occurredDateTime: ").append(toIndentedString(occurredDateTime)).append("\n");
    sb.append("    cfarOffersIds: ").append(toIndentedString(cfarOffersIds)).append("\n");
    sb.append("    uiVariant: ").append(toIndentedString(uiVariant)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("occurred_date_time");
    openapiFields.add("cfar_offers_ids");
    openapiFields.add("ui_variant");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("occurred_date_time");
    openapiRequiredFields.add("cfar_offers_ids");
    openapiRequiredFields.add("ui_variant");
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CfarOffersBannerDisplay
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CfarOffersBannerDisplay.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CfarOffersBannerDisplay is not found in the empty JSON string", CfarOffersBannerDisplay.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CfarOffersBannerDisplay.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CfarOffersBannerDisplay` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CfarOffersBannerDisplay.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("cfar_offers_ids") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("cfar_offers_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `cfar_offers_ids` to be an array in the JSON string but got `%s`", jsonObj.get("cfar_offers_ids").toString()));
      }
      // validate the required field `ui_variant`
      UiVariant.validateJsonElement(jsonObj.get("ui_variant"));
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CfarOffersBannerDisplay.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CfarOffersBannerDisplay' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CfarOffersBannerDisplay> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CfarOffersBannerDisplay.class));

       return (TypeAdapter<T>) new TypeAdapter<CfarOffersBannerDisplay>() {
           @Override
           public void write(JsonWriter out, CfarOffersBannerDisplay value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CfarOffersBannerDisplay read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CfarOffersBannerDisplay given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CfarOffersBannerDisplay
   * @throws IOException if the JSON string is invalid with respect to CfarOffersBannerDisplay
   */
  public static CfarOffersBannerDisplay fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CfarOffersBannerDisplay.class);
  }

  /**
   * Convert an instance of CfarOffersBannerDisplay to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

