/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.Ancillary;
import com.hopper.cloud.airlines.model.CfarItinerarySlice;
import com.hopper.cloud.airlines.model.CfarPassenger;
import com.hopper.cloud.airlines.model.CfarPassengerTax;
import com.hopper.cloud.airlines.model.FareRule;
import com.hopper.cloud.airlines.model.PassengerPricing;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * CfarItinerary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-02T18:35:20.974206513Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class CfarItinerary {
  public static final String SERIALIZED_NAME_PASSENGER_PRICING = "passenger_pricing";
  @SerializedName(SERIALIZED_NAME_PASSENGER_PRICING)
  @javax.annotation.Nonnull
  private List<PassengerPricing> passengerPricing;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nonnull
  private String currency;

  public static final String SERIALIZED_NAME_SLICES = "slices";
  @SerializedName(SERIALIZED_NAME_SLICES)
  @javax.annotation.Nonnull
  private List<CfarItinerarySlice> slices;

  public static final String SERIALIZED_NAME_ANCILLARIES = "ancillaries";
  @SerializedName(SERIALIZED_NAME_ANCILLARIES)
  @javax.annotation.Nullable
  private List<Ancillary> ancillaries;

  public static final String SERIALIZED_NAME_TOTAL_PRICE = "total_price";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
  @javax.annotation.Nullable
  private String totalPrice;

  public static final String SERIALIZED_NAME_PASSENGERS = "passengers";
  @SerializedName(SERIALIZED_NAME_PASSENGERS)
  @javax.annotation.Nullable
  private List<CfarPassenger> passengers;

  public static final String SERIALIZED_NAME_FARE_RULES = "fare_rules";
  @SerializedName(SERIALIZED_NAME_FARE_RULES)
  @javax.annotation.Nullable
  private List<FareRule> fareRules;

  public static final String SERIALIZED_NAME_TAXES = "taxes";
  @SerializedName(SERIALIZED_NAME_TAXES)
  @javax.annotation.Nullable
  private List<CfarPassengerTax> taxes;

  public CfarItinerary() {
  }

  public CfarItinerary passengerPricing(@javax.annotation.Nonnull List<PassengerPricing> passengerPricing) {
    this.passengerPricing = passengerPricing;
    return this;
  }

  public CfarItinerary addPassengerPricingItem(PassengerPricing passengerPricingItem) {
    if (this.passengerPricing == null) {
      this.passengerPricing = new ArrayList<>();
    }
    this.passengerPricing.add(passengerPricingItem);
    return this;
  }

  /**
   * List of passengers type, count and pricing for the itinerary
   * @return passengerPricing
   */
  @javax.annotation.Nonnull
  public List<PassengerPricing> getPassengerPricing() {
    return passengerPricing;
  }

  public void setPassengerPricing(@javax.annotation.Nonnull List<PassengerPricing> passengerPricing) {
    this.passengerPricing = passengerPricing;
  }


  public CfarItinerary currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency of pricing fields
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public CfarItinerary slices(@javax.annotation.Nonnull List<CfarItinerarySlice> slices) {
    this.slices = slices;
    return this;
  }

  public CfarItinerary addSlicesItem(CfarItinerarySlice slicesItem) {
    if (this.slices == null) {
      this.slices = new ArrayList<>();
    }
    this.slices.add(slicesItem);
    return this;
  }

  /**
   * List of slices of the itinerary; 1 (one way),  2 (round trip) or up to 10 (multi-destination) slices are allowed
   * @return slices
   */
  @javax.annotation.Nonnull
  public List<CfarItinerarySlice> getSlices() {
    return slices;
  }

  public void setSlices(@javax.annotation.Nonnull List<CfarItinerarySlice> slices) {
    this.slices = slices;
  }


  public CfarItinerary ancillaries(@javax.annotation.Nullable List<Ancillary> ancillaries) {
    this.ancillaries = ancillaries;
    return this;
  }

  public CfarItinerary addAncillariesItem(Ancillary ancillariesItem) {
    if (this.ancillaries == null) {
      this.ancillaries = new ArrayList<>();
    }
    this.ancillaries.add(ancillariesItem);
    return this;
  }

  /**
   * Ancillaries attached to the itinerary and their prices. Only ancillaries covered by CFAR must be filled
   * @return ancillaries
   */
  @javax.annotation.Nullable
  public List<Ancillary> getAncillaries() {
    return ancillaries;
  }

  public void setAncillaries(@javax.annotation.Nullable List<Ancillary> ancillaries) {
    this.ancillaries = ancillaries;
  }


  public CfarItinerary totalPrice(@javax.annotation.Nullable String totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

  /**
   * Total price to be covered by CFAR (including ancillaries if applicable)
   * @return totalPrice
   */
  @javax.annotation.Nullable
  public String getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(@javax.annotation.Nullable String totalPrice) {
    this.totalPrice = totalPrice;
  }


  public CfarItinerary passengers(@javax.annotation.Nullable List<CfarPassenger> passengers) {
    this.passengers = passengers;
    return this;
  }

  public CfarItinerary addPassengersItem(CfarPassenger passengersItem) {
    if (this.passengers == null) {
      this.passengers = new ArrayList<>();
    }
    this.passengers.add(passengersItem);
    return this;
  }

  /**
   * Details of the passengers
   * @return passengers
   */
  @javax.annotation.Nullable
  public List<CfarPassenger> getPassengers() {
    return passengers;
  }

  public void setPassengers(@javax.annotation.Nullable List<CfarPassenger> passengers) {
    this.passengers = passengers;
  }


  public CfarItinerary fareRules(@javax.annotation.Nullable List<FareRule> fareRules) {
    this.fareRules = fareRules;
    return this;
  }

  public CfarItinerary addFareRulesItem(FareRule fareRulesItem) {
    if (this.fareRules == null) {
      this.fareRules = new ArrayList<>();
    }
    this.fareRules.add(fareRulesItem);
    return this;
  }

  /**
   * The fare rules associated to the itinerary. If different fare rules apply to different slices in the itinerary, indicate the most restrictive.
   * @return fareRules
   */
  @javax.annotation.Nullable
  public List<FareRule> getFareRules() {
    return fareRules;
  }

  public void setFareRules(@javax.annotation.Nullable List<FareRule> fareRules) {
    this.fareRules = fareRules;
  }


  public CfarItinerary taxes(@javax.annotation.Nullable List<CfarPassengerTax> taxes) {
    this.taxes = taxes;
    return this;
  }

  public CfarItinerary addTaxesItem(CfarPassengerTax taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

  /**
   * Taxes applicable to this itinerary
   * @return taxes
   */
  @javax.annotation.Nullable
  public List<CfarPassengerTax> getTaxes() {
    return taxes;
  }

  public void setTaxes(@javax.annotation.Nullable List<CfarPassengerTax> taxes) {
    this.taxes = taxes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CfarItinerary cfarItinerary = (CfarItinerary) o;
    return Objects.equals(this.passengerPricing, cfarItinerary.passengerPricing) &&
        Objects.equals(this.currency, cfarItinerary.currency) &&
        Objects.equals(this.slices, cfarItinerary.slices) &&
        Objects.equals(this.ancillaries, cfarItinerary.ancillaries) &&
        Objects.equals(this.totalPrice, cfarItinerary.totalPrice) &&
        Objects.equals(this.passengers, cfarItinerary.passengers) &&
        Objects.equals(this.fareRules, cfarItinerary.fareRules) &&
        Objects.equals(this.taxes, cfarItinerary.taxes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerPricing, currency, slices, ancillaries, totalPrice, passengers, fareRules, taxes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CfarItinerary {\n");
    sb.append("    passengerPricing: ").append(toIndentedString(passengerPricing)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    slices: ").append(toIndentedString(slices)).append("\n");
    sb.append("    ancillaries: ").append(toIndentedString(ancillaries)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    passengers: ").append(toIndentedString(passengers)).append("\n");
    sb.append("    fareRules: ").append(toIndentedString(fareRules)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("passenger_pricing");
    openapiFields.add("currency");
    openapiFields.add("slices");
    openapiFields.add("ancillaries");
    openapiFields.add("total_price");
    openapiFields.add("passengers");
    openapiFields.add("fare_rules");
    openapiFields.add("taxes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("passenger_pricing");
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("slices");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CfarItinerary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CfarItinerary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CfarItinerary is not found in the empty JSON string", CfarItinerary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CfarItinerary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CfarItinerary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CfarItinerary.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("passenger_pricing").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `passenger_pricing` to be an array in the JSON string but got `%s`", jsonObj.get("passenger_pricing").toString()));
      }

      JsonArray jsonArraypassengerPricing = jsonObj.getAsJsonArray("passenger_pricing");
      // validate the required field `passenger_pricing` (array)
      for (int i = 0; i < jsonArraypassengerPricing.size(); i++) {
        PassengerPricing.validateJsonElement(jsonArraypassengerPricing.get(i));
      };
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("slices").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `slices` to be an array in the JSON string but got `%s`", jsonObj.get("slices").toString()));
      }

      JsonArray jsonArrayslices = jsonObj.getAsJsonArray("slices");
      // validate the required field `slices` (array)
      for (int i = 0; i < jsonArrayslices.size(); i++) {
        CfarItinerarySlice.validateJsonElement(jsonArrayslices.get(i));
      };
      if (jsonObj.get("ancillaries") != null && !jsonObj.get("ancillaries").isJsonNull()) {
        JsonArray jsonArrayancillaries = jsonObj.getAsJsonArray("ancillaries");
        if (jsonArrayancillaries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ancillaries").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ancillaries` to be an array in the JSON string but got `%s`", jsonObj.get("ancillaries").toString()));
          }

          // validate the optional field `ancillaries` (array)
          for (int i = 0; i < jsonArrayancillaries.size(); i++) {
            Ancillary.validateJsonElement(jsonArrayancillaries.get(i));
          };
        }
      }
      if ((jsonObj.get("total_price") != null && !jsonObj.get("total_price").isJsonNull()) && !jsonObj.get("total_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_price").toString()));
      }
      if (jsonObj.get("passengers") != null && !jsonObj.get("passengers").isJsonNull()) {
        JsonArray jsonArraypassengers = jsonObj.getAsJsonArray("passengers");
        if (jsonArraypassengers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("passengers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `passengers` to be an array in the JSON string but got `%s`", jsonObj.get("passengers").toString()));
          }

          // validate the optional field `passengers` (array)
          for (int i = 0; i < jsonArraypassengers.size(); i++) {
            CfarPassenger.validateJsonElement(jsonArraypassengers.get(i));
          };
        }
      }
      if (jsonObj.get("fare_rules") != null && !jsonObj.get("fare_rules").isJsonNull()) {
        JsonArray jsonArrayfareRules = jsonObj.getAsJsonArray("fare_rules");
        if (jsonArrayfareRules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fare_rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `fare_rules` to be an array in the JSON string but got `%s`", jsonObj.get("fare_rules").toString()));
          }

          // validate the optional field `fare_rules` (array)
          for (int i = 0; i < jsonArrayfareRules.size(); i++) {
            FareRule.validateJsonElement(jsonArrayfareRules.get(i));
          };
        }
      }
      if (jsonObj.get("taxes") != null && !jsonObj.get("taxes").isJsonNull()) {
        JsonArray jsonArraytaxes = jsonObj.getAsJsonArray("taxes");
        if (jsonArraytaxes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taxes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `taxes` to be an array in the JSON string but got `%s`", jsonObj.get("taxes").toString()));
          }

          // validate the optional field `taxes` (array)
          for (int i = 0; i < jsonArraytaxes.size(); i++) {
            CfarPassengerTax.validateJsonElement(jsonArraytaxes.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CfarItinerary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CfarItinerary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CfarItinerary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CfarItinerary.class));

       return (TypeAdapter<T>) new TypeAdapter<CfarItinerary>() {
           @Override
           public void write(JsonWriter out, CfarItinerary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CfarItinerary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CfarItinerary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CfarItinerary
   * @throws IOException if the JSON string is invalid with respect to CfarItinerary
   */
  public static CfarItinerary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CfarItinerary.class);
  }

  /**
   * Convert an instance of CfarItinerary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

