/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.DgContents;
import com.hopper.cloud.airlines.model.DgItinerary;
import com.hopper.cloud.airlines.model.DgRequestType;
import com.hopper.cloud.airlines.model.DgTax;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * A created Dg offer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CreateDgOfferItemResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
    private String id;

  public static final String SERIALIZED_NAME_PREMIUM = "premium";
  @SerializedName(SERIALIZED_NAME_PREMIUM)
    private String premium;

  public static final String SERIALIZED_NAME_COVERAGE = "coverage";
  @SerializedName(SERIALIZED_NAME_COVERAGE)
    private String coverage;

  public static final String SERIALIZED_NAME_COVERAGE_PERCENTAGE = "coverage_percentage";
  @SerializedName(SERIALIZED_NAME_COVERAGE_PERCENTAGE)
    private String coveragePercentage;

  public static final String SERIALIZED_NAME_SERVICE_CAP = "service_cap";
  @SerializedName(SERIALIZED_NAME_SERVICE_CAP)
    private String serviceCap;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
    private String currency;

  public static final String SERIALIZED_NAME_TAXES_TOTAL = "taxes_total";
  @SerializedName(SERIALIZED_NAME_TAXES_TOTAL)
    private String taxesTotal;

  public static final String SERIALIZED_NAME_TAXES = "taxes";
  @SerializedName(SERIALIZED_NAME_TAXES)
  @javax.annotation.Nullable
  private List<DgTax> taxes = new ArrayList<>();

  public static final String SERIALIZED_NAME_REQUEST_TYPE = "request_type";
  @SerializedName(SERIALIZED_NAME_REQUEST_TYPE)
    private DgRequestType requestType;

  public static final String SERIALIZED_NAME_MAX_HOURS_BEFORE_DEPARTURE = "max_hours_before_departure";
  @SerializedName(SERIALIZED_NAME_MAX_HOURS_BEFORE_DEPARTURE)
    private Integer maxHoursBeforeDeparture;

  public static final String SERIALIZED_NAME_MIN_MINUTES_DELAY = "min_minutes_delay";
  @SerializedName(SERIALIZED_NAME_MIN_MINUTES_DELAY)
    private Integer minMinutesDelay;

  public static final String SERIALIZED_NAME_CREATED_DATE_TIME = "created_date_time";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE_TIME)
    private OffsetDateTime createdDateTime;

  public static final String SERIALIZED_NAME_CONTRACT_EXPIRY_DATE_TIME = "contract_expiry_date_time";
  @SerializedName(SERIALIZED_NAME_CONTRACT_EXPIRY_DATE_TIME)
    private OffsetDateTime contractExpiryDateTime;

  public static final String SERIALIZED_NAME_ITINERARY = "itinerary";
  @SerializedName(SERIALIZED_NAME_ITINERARY)
    private DgItinerary itinerary;

  public static final String SERIALIZED_NAME_EXT_ATTRIBUTES = "ext_attributes";
  @SerializedName(SERIALIZED_NAME_EXT_ATTRIBUTES)
    private Map<String, String> extAttributes = new HashMap<>();

  public static final String SERIALIZED_NAME_CONTENTS = "contents";
  @SerializedName(SERIALIZED_NAME_CONTENTS)
    private Map<String, DgContents> contents = new HashMap<>();

  public static final String SERIALIZED_NAME_MERCHANDISING_URL = "merchandising_url";
  @SerializedName(SERIALIZED_NAME_MERCHANDISING_URL)
  @javax.annotation.Nullable
  private String merchandisingUrl;

  public CreateDgOfferItemResponse() {
  }

  public CreateDgOfferItemResponse id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for an offer
   * @return id
   */
    public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public CreateDgOfferItemResponse premium(String premium) {
    this.premium = premium;
    return this;
  }

  /**
   * Total amount to be paid for DG
   * @return premium
   */
    public String getPremium() {
    return premium;
  }

  public void setPremium(String premium) {
    this.premium = premium;
  }


  public CreateDgOfferItemResponse coverage(String coverage) {
    this.coverage = coverage;
    return this;
  }

  /**
   * Total amount to be refunded upon DG exercise
   * @return coverage
   */
    public String getCoverage() {
    return coverage;
  }

  public void setCoverage(String coverage) {
    this.coverage = coverage;
  }


  public CreateDgOfferItemResponse coveragePercentage(String coveragePercentage) {
    this.coveragePercentage = coveragePercentage;
    return this;
  }

  /**
   * Percentage of the ticket’s value to be refunded upon DG exercise
   * @return coveragePercentage
   */
    public String getCoveragePercentage() {
    return coveragePercentage;
  }

  public void setCoveragePercentage(String coveragePercentage) {
    this.coveragePercentage = coveragePercentage;
  }


  public CreateDgOfferItemResponse serviceCap(String serviceCap) {
    this.serviceCap = serviceCap;
    return this;
  }

  /**
   * Get serviceCap
   * @return serviceCap
   */
    public String getServiceCap() {
    return serviceCap;
  }

  public void setServiceCap(String serviceCap) {
    this.serviceCap = serviceCap;
  }


  public CreateDgOfferItemResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency of offer
   * @return currency
   */
    public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public CreateDgOfferItemResponse taxesTotal(String taxesTotal) {
    this.taxesTotal = taxesTotal;
    return this;
  }

  /**
   * Total of applicable taxes
   * @return taxesTotal
   */
    public String getTaxesTotal() {
    return taxesTotal;
  }

  public void setTaxesTotal(String taxesTotal) {
    this.taxesTotal = taxesTotal;
  }


  public CreateDgOfferItemResponse taxes(@javax.annotation.Nullable List<DgTax> taxes) {
    this.taxes = taxes;
    return this;
  }

  public CreateDgOfferItemResponse addTaxesItem(DgTax taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

  /**
   * List of applicable taxes
   * @return taxes
   */
  @javax.annotation.Nullable
  public List<DgTax> getTaxes() {
    return taxes;
  }

  public void setTaxes(@javax.annotation.Nullable List<DgTax> taxes) {
    this.taxes = taxes;
  }


  public CreateDgOfferItemResponse requestType(DgRequestType requestType) {
    this.requestType = requestType;
    return this;
  }

  /**
   * Get requestType
   * @return requestType
   */
    public DgRequestType getRequestType() {
    return requestType;
  }

  public void setRequestType(DgRequestType requestType) {
    this.requestType = requestType;
  }


  public CreateDgOfferItemResponse maxHoursBeforeDeparture(Integer maxHoursBeforeDeparture) {
    this.maxHoursBeforeDeparture = maxHoursBeforeDeparture;
    return this;
  }

  /**
   * The number of hours before each flight or slice departure from which a purchased contract would start to cover disruptions
   * minimum: 0
   * @return maxHoursBeforeDeparture
   */
    public Integer getMaxHoursBeforeDeparture() {
    return maxHoursBeforeDeparture;
  }

  public void setMaxHoursBeforeDeparture(Integer maxHoursBeforeDeparture) {
    this.maxHoursBeforeDeparture = maxHoursBeforeDeparture;
  }


  public CreateDgOfferItemResponse minMinutesDelay(Integer minMinutesDelay) {
    this.minMinutesDelay = minMinutesDelay;
    return this;
  }

  /**
   * The minimum flight or slice departure delay in minutes to be covered
   * minimum: 0
   * @return minMinutesDelay
   */
    public Integer getMinMinutesDelay() {
    return minMinutesDelay;
  }

  public void setMinMinutesDelay(Integer minMinutesDelay) {
    this.minMinutesDelay = minMinutesDelay;
  }


  public CreateDgOfferItemResponse createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

  /**
   * A UTC [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) datetime; the date and time at which a DG offer was created
   * @return createdDateTime
   */
    public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }


  public CreateDgOfferItemResponse contractExpiryDateTime(OffsetDateTime contractExpiryDateTime) {
    this.contractExpiryDateTime = contractExpiryDateTime;
    return this;
  }

  /**
   * A UTC [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) datetime; the date and time at which the DG contract will expire once purchased
   * @return contractExpiryDateTime
   */
    public OffsetDateTime getContractExpiryDateTime() {
    return contractExpiryDateTime;
  }

  public void setContractExpiryDateTime(OffsetDateTime contractExpiryDateTime) {
    this.contractExpiryDateTime = contractExpiryDateTime;
  }


  public CreateDgOfferItemResponse itinerary(DgItinerary itinerary) {
    this.itinerary = itinerary;
    return this;
  }

  /**
   * Get itinerary
   * @return itinerary
   */
    public DgItinerary getItinerary() {
    return itinerary;
  }

  public void setItinerary(DgItinerary itinerary) {
    this.itinerary = itinerary;
  }


  public CreateDgOfferItemResponse extAttributes(Map<String, String> extAttributes) {
    this.extAttributes = extAttributes;
    return this;
  }

  public CreateDgOfferItemResponse putExtAttributesItem(String key, String extAttributesItem) {
    if (this.extAttributes == null) {
      this.extAttributes = new HashMap<>();
    }
    this.extAttributes.put(key, extAttributesItem);
    return this;
  }

  /**
   * Get extAttributes
   * @return extAttributes
   */
    public Map<String, String> getExtAttributes() {
    return extAttributes;
  }

  public void setExtAttributes(Map<String, String> extAttributes) {
    this.extAttributes = extAttributes;
  }


  public CreateDgOfferItemResponse contents(Map<String, DgContents> contents) {
    this.contents = contents;
    return this;
  }

  public CreateDgOfferItemResponse putContentsItem(String key, DgContents contentsItem) {
    if (this.contents == null) {
      this.contents = new HashMap<>();
    }
    this.contents.put(key, contentsItem);
    return this;
  }

  /**
   * Get contents
   * @return contents
   */
    public Map<String, DgContents> getContents() {
    return contents;
  }

  public void setContents(Map<String, DgContents> contents) {
    this.contents = contents;
  }


  public CreateDgOfferItemResponse merchandisingUrl(@javax.annotation.Nullable String merchandisingUrl) {
    this.merchandisingUrl = merchandisingUrl;
    return this;
  }

  /**
   * The url for rendering offer merchandising
   * @return merchandisingUrl
   */
  @javax.annotation.Nullable
  public String getMerchandisingUrl() {
    return merchandisingUrl;
  }

  public void setMerchandisingUrl(@javax.annotation.Nullable String merchandisingUrl) {
    this.merchandisingUrl = merchandisingUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDgOfferItemResponse createDgOfferItemResponse = (CreateDgOfferItemResponse) o;
    return Objects.equals(this.id, createDgOfferItemResponse.id) &&
        Objects.equals(this.premium, createDgOfferItemResponse.premium) &&
        Objects.equals(this.coverage, createDgOfferItemResponse.coverage) &&
        Objects.equals(this.coveragePercentage, createDgOfferItemResponse.coveragePercentage) &&
        Objects.equals(this.serviceCap, createDgOfferItemResponse.serviceCap) &&
        Objects.equals(this.currency, createDgOfferItemResponse.currency) &&
        Objects.equals(this.taxesTotal, createDgOfferItemResponse.taxesTotal) &&
        Objects.equals(this.taxes, createDgOfferItemResponse.taxes) &&
        Objects.equals(this.requestType, createDgOfferItemResponse.requestType) &&
        Objects.equals(this.maxHoursBeforeDeparture, createDgOfferItemResponse.maxHoursBeforeDeparture) &&
        Objects.equals(this.minMinutesDelay, createDgOfferItemResponse.minMinutesDelay) &&
        Objects.equals(this.createdDateTime, createDgOfferItemResponse.createdDateTime) &&
        Objects.equals(this.contractExpiryDateTime, createDgOfferItemResponse.contractExpiryDateTime) &&
        Objects.equals(this.itinerary, createDgOfferItemResponse.itinerary) &&
        Objects.equals(this.extAttributes, createDgOfferItemResponse.extAttributes) &&
        Objects.equals(this.contents, createDgOfferItemResponse.contents) &&
        Objects.equals(this.merchandisingUrl, createDgOfferItemResponse.merchandisingUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, premium, coverage, coveragePercentage, serviceCap, currency, taxesTotal, taxes, requestType, maxHoursBeforeDeparture, minMinutesDelay, createdDateTime, contractExpiryDateTime, itinerary, extAttributes, contents, merchandisingUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDgOfferItemResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    coverage: ").append(toIndentedString(coverage)).append("\n");
    sb.append("    coveragePercentage: ").append(toIndentedString(coveragePercentage)).append("\n");
    sb.append("    serviceCap: ").append(toIndentedString(serviceCap)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    taxesTotal: ").append(toIndentedString(taxesTotal)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    maxHoursBeforeDeparture: ").append(toIndentedString(maxHoursBeforeDeparture)).append("\n");
    sb.append("    minMinutesDelay: ").append(toIndentedString(minMinutesDelay)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    contractExpiryDateTime: ").append(toIndentedString(contractExpiryDateTime)).append("\n");
    sb.append("    itinerary: ").append(toIndentedString(itinerary)).append("\n");
    sb.append("    extAttributes: ").append(toIndentedString(extAttributes)).append("\n");
    sb.append("    contents: ").append(toIndentedString(contents)).append("\n");
    sb.append("    merchandisingUrl: ").append(toIndentedString(merchandisingUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("premium");
    openapiFields.add("coverage");
    openapiFields.add("coverage_percentage");
    openapiFields.add("service_cap");
    openapiFields.add("currency");
    openapiFields.add("taxes_total");
    openapiFields.add("taxes");
    openapiFields.add("request_type");
    openapiFields.add("max_hours_before_departure");
    openapiFields.add("min_minutes_delay");
    openapiFields.add("created_date_time");
    openapiFields.add("contract_expiry_date_time");
    openapiFields.add("itinerary");
    openapiFields.add("ext_attributes");
    openapiFields.add("contents");
    openapiFields.add("merchandising_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("premium");
    openapiRequiredFields.add("coverage");
    openapiRequiredFields.add("coverage_percentage");
    openapiRequiredFields.add("service_cap");
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("taxes_total");
    openapiRequiredFields.add("request_type");
    openapiRequiredFields.add("max_hours_before_departure");
    openapiRequiredFields.add("min_minutes_delay");
    openapiRequiredFields.add("created_date_time");
    openapiRequiredFields.add("contract_expiry_date_time");
    openapiRequiredFields.add("itinerary");
    openapiRequiredFields.add("ext_attributes");
    openapiRequiredFields.add("contents");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDgOfferItemResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDgOfferItemResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateDgOfferItemResponse is not found in the empty JSON string", CreateDgOfferItemResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDgOfferItemResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateDgOfferItemResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateDgOfferItemResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("premium").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `premium` to be a primitive type in the JSON string but got `%s`", jsonObj.get("premium").toString()));
      }
      if (!jsonObj.get("coverage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `coverage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("coverage").toString()));
      }
      if (!jsonObj.get("coverage_percentage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `coverage_percentage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("coverage_percentage").toString()));
      }
      if (!jsonObj.get("service_cap").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `service_cap` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service_cap").toString()));
      }
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if (!jsonObj.get("taxes_total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxes_total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taxes_total").toString()));
      }
      if (jsonObj.get("taxes") != null && !jsonObj.get("taxes").isJsonNull()) {
        JsonArray jsonArraytaxes = jsonObj.getAsJsonArray("taxes");
        if (jsonArraytaxes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taxes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `taxes` to be an array in the JSON string but got `%s`", jsonObj.get("taxes").toString()));
          }

          // validate the optional field `taxes` (array)
          for (int i = 0; i < jsonArraytaxes.size(); i++) {
            DgTax.validateJsonElement(jsonArraytaxes.get(i));
          };
        }
      }
      // validate the required field `request_type`
      DgRequestType.validateJsonElement(jsonObj.get("request_type"));
      // validate the required field `itinerary`
      DgItinerary.validateJsonElement(jsonObj.get("itinerary"));
      if ((jsonObj.get("merchandising_url") != null && !jsonObj.get("merchandising_url").isJsonNull()) && !jsonObj.get("merchandising_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchandising_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchandising_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDgOfferItemResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDgOfferItemResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDgOfferItemResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDgOfferItemResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDgOfferItemResponse>() {
           @Override
           public void write(JsonWriter out, CreateDgOfferItemResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDgOfferItemResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDgOfferItemResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDgOfferItemResponse
   * @throws IOException if the JSON string is invalid with respect to CreateDgOfferItemResponse
   */
  public static CreateDgOfferItemResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDgOfferItemResponse.class);
  }

  /**
   * Convert an instance of CreateDgOfferItemResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

