/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.CfarOfferItinerary;
import com.hopper.cloud.airlines.model.CreateAirlineCfarSessionRequest;
import com.hopper.cloud.airlines.model.RequestType;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * CreateCfarOfferRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-02T17:40:08.115903591Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class CreateCfarOfferRequest {
  public static final String SERIALIZED_NAME_ITINERARY = "itinerary";
  @SerializedName(SERIALIZED_NAME_ITINERARY)
  @javax.annotation.Nonnull
  private List<CfarOfferItinerary> itinerary = new ArrayList<>();

  public static final String SERIALIZED_NAME_REQUEST_TYPE = "request_type";
  @SerializedName(SERIALIZED_NAME_REQUEST_TYPE)
  @javax.annotation.Nonnull
  private RequestType requestType;

  public static final String SERIALIZED_NAME_BOOKING_DATE_TIME = "booking_date_time";
  @SerializedName(SERIALIZED_NAME_BOOKING_DATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime bookingDateTime;

  public static final String SERIALIZED_NAME_EXT_ATTRIBUTES = "ext_attributes";
  @SerializedName(SERIALIZED_NAME_EXT_ATTRIBUTES)
  @javax.annotation.Nonnull
  private Map<String, String> extAttributes = new HashMap<>();

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  @javax.annotation.Nullable
  private CreateAirlineCfarSessionRequest session;

  public CreateCfarOfferRequest() {
  }

  public CreateCfarOfferRequest itinerary(@javax.annotation.Nonnull List<CfarOfferItinerary> itinerary) {
    this.itinerary = itinerary;
    return this;
  }

  public CreateCfarOfferRequest addItineraryItem(CfarOfferItinerary itineraryItem) {
    if (this.itinerary == null) {
      this.itinerary = new ArrayList<>();
    }
    this.itinerary.add(itineraryItem);
    return this;
  }

  /**
   * An object detailing the itinerary and fare used to create a CFAR offer
   * @return itinerary
   */
  @javax.annotation.Nonnull
  public List<CfarOfferItinerary> getItinerary() {
    return itinerary;
  }

  public void setItinerary(@javax.annotation.Nonnull List<CfarOfferItinerary> itinerary) {
    this.itinerary = itinerary;
  }


  public CreateCfarOfferRequest requestType(@javax.annotation.Nonnull RequestType requestType) {
    this.requestType = requestType;
    return this;
  }

  /**
   * Get requestType
   * @return requestType
   */
  @javax.annotation.Nonnull
  public RequestType getRequestType() {
    return requestType;
  }

  public void setRequestType(@javax.annotation.Nonnull RequestType requestType) {
    this.requestType = requestType;
  }


  public CreateCfarOfferRequest bookingDateTime(@javax.annotation.Nullable OffsetDateTime bookingDateTime) {
    this.bookingDateTime = bookingDateTime;
    return this;
  }

  /**
   * A UTC RFC3339 datetime; the date and time at which the booking was made. To be used only with the request type \&quot;post_booking\&quot;
   * @return bookingDateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getBookingDateTime() {
    return bookingDateTime;
  }

  public void setBookingDateTime(@javax.annotation.Nullable OffsetDateTime bookingDateTime) {
    this.bookingDateTime = bookingDateTime;
  }


  public CreateCfarOfferRequest extAttributes(@javax.annotation.Nonnull Map<String, String> extAttributes) {
    this.extAttributes = extAttributes;
    return this;
  }

  public CreateCfarOfferRequest putExtAttributesItem(String key, String extAttributesItem) {
    if (this.extAttributes == null) {
      this.extAttributes = new HashMap<>();
    }
    this.extAttributes.put(key, extAttributesItem);
    return this;
  }

  /**
   * Get extAttributes
   * @return extAttributes
   */
  @javax.annotation.Nonnull
  public Map<String, String> getExtAttributes() {
    return extAttributes;
  }

  public void setExtAttributes(@javax.annotation.Nonnull Map<String, String> extAttributes) {
    this.extAttributes = extAttributes;
  }


  public CreateCfarOfferRequest session(@javax.annotation.Nullable CreateAirlineCfarSessionRequest session) {
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @javax.annotation.Nullable
  public CreateAirlineCfarSessionRequest getSession() {
    return session;
  }

  public void setSession(@javax.annotation.Nullable CreateAirlineCfarSessionRequest session) {
    this.session = session;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCfarOfferRequest createCfarOfferRequest = (CreateCfarOfferRequest) o;
    return Objects.equals(this.itinerary, createCfarOfferRequest.itinerary) &&
        Objects.equals(this.requestType, createCfarOfferRequest.requestType) &&
        Objects.equals(this.bookingDateTime, createCfarOfferRequest.bookingDateTime) &&
        Objects.equals(this.extAttributes, createCfarOfferRequest.extAttributes) &&
        Objects.equals(this.session, createCfarOfferRequest.session);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itinerary, requestType, bookingDateTime, extAttributes, session);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCfarOfferRequest {\n");
    sb.append("    itinerary: ").append(toIndentedString(itinerary)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    bookingDateTime: ").append(toIndentedString(bookingDateTime)).append("\n");
    sb.append("    extAttributes: ").append(toIndentedString(extAttributes)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("itinerary");
    openapiFields.add("request_type");
    openapiFields.add("booking_date_time");
    openapiFields.add("ext_attributes");
    openapiFields.add("session");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("itinerary");
    openapiRequiredFields.add("request_type");
    openapiRequiredFields.add("ext_attributes");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateCfarOfferRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateCfarOfferRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateCfarOfferRequest is not found in the empty JSON string", CreateCfarOfferRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateCfarOfferRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateCfarOfferRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateCfarOfferRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("itinerary").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `itinerary` to be an array in the JSON string but got `%s`", jsonObj.get("itinerary").toString()));
      }

      JsonArray jsonArrayitinerary = jsonObj.getAsJsonArray("itinerary");
      // validate the required field `itinerary` (array)
      for (int i = 0; i < jsonArrayitinerary.size(); i++) {
        CfarOfferItinerary.validateJsonElement(jsonArrayitinerary.get(i));
      };
      // validate the required field `request_type`
      RequestType.validateJsonElement(jsonObj.get("request_type"));
      // validate the optional field `session`
      if (jsonObj.get("session") != null && !jsonObj.get("session").isJsonNull()) {
        CreateAirlineCfarSessionRequest.validateJsonElement(jsonObj.get("session"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateCfarOfferRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateCfarOfferRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateCfarOfferRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateCfarOfferRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateCfarOfferRequest>() {
           @Override
           public void write(JsonWriter out, CreateCfarOfferRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateCfarOfferRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateCfarOfferRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateCfarOfferRequest
   * @throws IOException if the JSON string is invalid with respect to CreateCfarOfferRequest
   */
  public static CreateCfarOfferRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateCfarOfferRequest.class);
  }

  /**
   * Convert an instance of CreateCfarOfferRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

