/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.DgAncillaryType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * An object detailing the fare used to create a DG offer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DgAncillary {
  public static final String SERIALIZED_NAME_TOTAL_PRICE = "total_price";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
    private String totalPrice;

  public static final String SERIALIZED_NAME_PASSENGER_REFERENCE = "passenger_reference";
  @SerializedName(SERIALIZED_NAME_PASSENGER_REFERENCE)
  @javax.annotation.Nullable
  private String passengerReference;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
    private DgAncillaryType type;

  public static final String SERIALIZED_NAME_COVERED = "covered";
  @SerializedName(SERIALIZED_NAME_COVERED)
  @javax.annotation.Nullable
  private Boolean covered;

  public DgAncillary() {
  }

  public DgAncillary totalPrice(String totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

  /**
   * Total price of ancillaries of this type
   * @return totalPrice
   */
    public String getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(String totalPrice) {
    this.totalPrice = totalPrice;
  }


  public DgAncillary passengerReference(@javax.annotation.Nullable String passengerReference) {
    this.passengerReference = passengerReference;
    return this;
  }

  /**
   * Unique reference of the passenger associated to this ancillary
   * @return passengerReference
   */
  @javax.annotation.Nullable
  public String getPassengerReference() {
    return passengerReference;
  }

  public void setPassengerReference(@javax.annotation.Nullable String passengerReference) {
    this.passengerReference = passengerReference;
  }


  public DgAncillary type(DgAncillaryType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
    public DgAncillaryType getType() {
    return type;
  }

  public void setType(DgAncillaryType type) {
    this.type = type;
  }


  public DgAncillary covered(@javax.annotation.Nullable Boolean covered) {
    this.covered = covered;
    return this;
  }

  /**
   * Is this ancillary covered by the product. By default true if not specified
   * @return covered
   */
  @javax.annotation.Nullable
  public Boolean getCovered() {
    return covered;
  }

  public void setCovered(@javax.annotation.Nullable Boolean covered) {
    this.covered = covered;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DgAncillary dgAncillary = (DgAncillary) o;
    return Objects.equals(this.totalPrice, dgAncillary.totalPrice) &&
        Objects.equals(this.passengerReference, dgAncillary.passengerReference) &&
        Objects.equals(this.type, dgAncillary.type) &&
        Objects.equals(this.covered, dgAncillary.covered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPrice, passengerReference, type, covered);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DgAncillary {\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    passengerReference: ").append(toIndentedString(passengerReference)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    covered: ").append(toIndentedString(covered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("total_price");
    openapiFields.add("passenger_reference");
    openapiFields.add("type");
    openapiFields.add("covered");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("total_price");
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DgAncillary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DgAncillary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DgAncillary is not found in the empty JSON string", DgAncillary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DgAncillary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DgAncillary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DgAncillary.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("total_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_price").toString()));
      }
      if ((jsonObj.get("passenger_reference") != null && !jsonObj.get("passenger_reference").isJsonNull()) && !jsonObj.get("passenger_reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `passenger_reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("passenger_reference").toString()));
      }
      // validate the required field `type`
      DgAncillaryType.validateJsonElement(jsonObj.get("type"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DgAncillary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DgAncillary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DgAncillary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DgAncillary.class));

       return (TypeAdapter<T>) new TypeAdapter<DgAncillary>() {
           @Override
           public void write(JsonWriter out, DgAncillary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DgAncillary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DgAncillary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DgAncillary
   * @throws IOException if the JSON string is invalid with respect to DgAncillary
   */
  public static DgAncillary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DgAncillary.class);
  }

  /**
   * Convert an instance of DgAncillary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

