/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.ExerciseStepResult;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * DgExercisePortalComplete
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-02T18:35:20.974206513Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class DgExercisePortalComplete {
  public static final String SERIALIZED_NAME_OCCURRED_DATE_TIME = "occurred_date_time";
  @SerializedName(SERIALIZED_NAME_OCCURRED_DATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime occurredDateTime;

  public static final String SERIALIZED_NAME_DG_EXERCISE_ID = "dg_exercise_id";
  @SerializedName(SERIALIZED_NAME_DG_EXERCISE_ID)
  @javax.annotation.Nonnull
  private String dgExerciseId;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  @javax.annotation.Nonnull
  private ExerciseStepResult result;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public DgExercisePortalComplete() {
  }

  public DgExercisePortalComplete occurredDateTime(@javax.annotation.Nonnull OffsetDateTime occurredDateTime) {
    this.occurredDateTime = occurredDateTime;
    return this;
  }

  /**
   * A UTC [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) datetime;  the date and time at which an event occurred on a client device
   * @return occurredDateTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getOccurredDateTime() {
    return occurredDateTime;
  }

  public void setOccurredDateTime(@javax.annotation.Nonnull OffsetDateTime occurredDateTime) {
    this.occurredDateTime = occurredDateTime;
  }


  public DgExercisePortalComplete dgExerciseId(@javax.annotation.Nonnull String dgExerciseId) {
    this.dgExerciseId = dgExerciseId;
    return this;
  }

  /**
   * Unique identifier for a DG exercise
   * @return dgExerciseId
   */
  @javax.annotation.Nonnull
  public String getDgExerciseId() {
    return dgExerciseId;
  }

  public void setDgExerciseId(@javax.annotation.Nonnull String dgExerciseId) {
    this.dgExerciseId = dgExerciseId;
  }


  public DgExercisePortalComplete result(@javax.annotation.Nonnull ExerciseStepResult result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @javax.annotation.Nonnull
  public ExerciseStepResult getResult() {
    return result;
  }

  public void setResult(@javax.annotation.Nonnull ExerciseStepResult result) {
    this.result = result;
  }


  public DgExercisePortalComplete type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DgExercisePortalComplete dgExercisePortalComplete = (DgExercisePortalComplete) o;
    return Objects.equals(this.occurredDateTime, dgExercisePortalComplete.occurredDateTime) &&
        Objects.equals(this.dgExerciseId, dgExercisePortalComplete.dgExerciseId) &&
        Objects.equals(this.result, dgExercisePortalComplete.result) &&
        Objects.equals(this.type, dgExercisePortalComplete.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(occurredDateTime, dgExerciseId, result, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DgExercisePortalComplete {\n");
    sb.append("    occurredDateTime: ").append(toIndentedString(occurredDateTime)).append("\n");
    sb.append("    dgExerciseId: ").append(toIndentedString(dgExerciseId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("occurred_date_time");
    openapiFields.add("dg_exercise_id");
    openapiFields.add("result");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("occurred_date_time");
    openapiRequiredFields.add("dg_exercise_id");
    openapiRequiredFields.add("result");
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DgExercisePortalComplete
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DgExercisePortalComplete.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DgExercisePortalComplete is not found in the empty JSON string", DgExercisePortalComplete.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DgExercisePortalComplete.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DgExercisePortalComplete` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DgExercisePortalComplete.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("dg_exercise_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dg_exercise_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dg_exercise_id").toString()));
      }
      // validate the required field `result`
      ExerciseStepResult.validateJsonElement(jsonObj.get("result"));
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DgExercisePortalComplete.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DgExercisePortalComplete' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DgExercisePortalComplete> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DgExercisePortalComplete.class));

       return (TypeAdapter<T>) new TypeAdapter<DgExercisePortalComplete>() {
           @Override
           public void write(JsonWriter out, DgExercisePortalComplete value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DgExercisePortalComplete read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DgExercisePortalComplete given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DgExercisePortalComplete
   * @throws IOException if the JSON string is invalid with respect to DgExercisePortalComplete
   */
  public static DgExercisePortalComplete fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DgExercisePortalComplete.class);
  }

  /**
   * Convert an instance of DgExercisePortalComplete to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

