/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.DgItinerarySliceSegment;
import com.hopper.cloud.airlines.model.DgPassengerPricing;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * An object containing the list of flight segments for a fare slice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-02T18:35:20.974206513Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class DgItinerarySlice {
  public static final String SERIALIZED_NAME_SEGMENTS = "segments";
  @SerializedName(SERIALIZED_NAME_SEGMENTS)
  @javax.annotation.Nonnull
  private List<DgItinerarySliceSegment> segments;

  public static final String SERIALIZED_NAME_FARE_BRAND = "fare_brand";
  @SerializedName(SERIALIZED_NAME_FARE_BRAND)
  @javax.annotation.Nullable
  private String fareBrand;

  public static final String SERIALIZED_NAME_PASSENGER_PRICING = "passenger_pricing";
  @SerializedName(SERIALIZED_NAME_PASSENGER_PRICING)
  @javax.annotation.Nullable
  private List<DgPassengerPricing> passengerPricing;

  public DgItinerarySlice() {
  }

  public DgItinerarySlice segments(@javax.annotation.Nonnull List<DgItinerarySliceSegment> segments) {
    this.segments = segments;
    return this;
  }

  public DgItinerarySlice addSegmentsItem(DgItinerarySliceSegment segmentsItem) {
    if (this.segments == null) {
      this.segments = new ArrayList<>();
    }
    this.segments.add(segmentsItem);
    return this;
  }

  /**
   * A list of segments which make up the slice
   * @return segments
   */
  @javax.annotation.Nonnull
  public List<DgItinerarySliceSegment> getSegments() {
    return segments;
  }

  public void setSegments(@javax.annotation.Nonnull List<DgItinerarySliceSegment> segments) {
    this.segments = segments;
  }


  public DgItinerarySlice fareBrand(@javax.annotation.Nullable String fareBrand) {
    this.fareBrand = fareBrand;
    return this;
  }

  /**
   * Name of the fare brand on the slice
   * @return fareBrand
   */
  @javax.annotation.Nullable
  public String getFareBrand() {
    return fareBrand;
  }

  public void setFareBrand(@javax.annotation.Nullable String fareBrand) {
    this.fareBrand = fareBrand;
  }


  public DgItinerarySlice passengerPricing(@javax.annotation.Nullable List<DgPassengerPricing> passengerPricing) {
    this.passengerPricing = passengerPricing;
    return this;
  }

  public DgItinerarySlice addPassengerPricingItem(DgPassengerPricing passengerPricingItem) {
    if (this.passengerPricing == null) {
      this.passengerPricing = new ArrayList<>();
    }
    this.passengerPricing.add(passengerPricingItem);
    return this;
  }

  /**
   * List of passengers type, count and pricing for the current slice
   * @return passengerPricing
   */
  @javax.annotation.Nullable
  public List<DgPassengerPricing> getPassengerPricing() {
    return passengerPricing;
  }

  public void setPassengerPricing(@javax.annotation.Nullable List<DgPassengerPricing> passengerPricing) {
    this.passengerPricing = passengerPricing;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DgItinerarySlice dgItinerarySlice = (DgItinerarySlice) o;
    return Objects.equals(this.segments, dgItinerarySlice.segments) &&
        Objects.equals(this.fareBrand, dgItinerarySlice.fareBrand) &&
        Objects.equals(this.passengerPricing, dgItinerarySlice.passengerPricing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(segments, fareBrand, passengerPricing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DgItinerarySlice {\n");
    sb.append("    segments: ").append(toIndentedString(segments)).append("\n");
    sb.append("    fareBrand: ").append(toIndentedString(fareBrand)).append("\n");
    sb.append("    passengerPricing: ").append(toIndentedString(passengerPricing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("segments");
    openapiFields.add("fare_brand");
    openapiFields.add("passenger_pricing");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("segments");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DgItinerarySlice
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DgItinerarySlice.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DgItinerarySlice is not found in the empty JSON string", DgItinerarySlice.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DgItinerarySlice.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DgItinerarySlice` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DgItinerarySlice.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("segments").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `segments` to be an array in the JSON string but got `%s`", jsonObj.get("segments").toString()));
      }

      JsonArray jsonArraysegments = jsonObj.getAsJsonArray("segments");
      // validate the required field `segments` (array)
      for (int i = 0; i < jsonArraysegments.size(); i++) {
        DgItinerarySliceSegment.validateJsonElement(jsonArraysegments.get(i));
      };
      if ((jsonObj.get("fare_brand") != null && !jsonObj.get("fare_brand").isJsonNull()) && !jsonObj.get("fare_brand").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fare_brand` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fare_brand").toString()));
      }
      if (jsonObj.get("passenger_pricing") != null && !jsonObj.get("passenger_pricing").isJsonNull()) {
        JsonArray jsonArraypassengerPricing = jsonObj.getAsJsonArray("passenger_pricing");
        if (jsonArraypassengerPricing != null) {
          // ensure the json data is an array
          if (!jsonObj.get("passenger_pricing").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `passenger_pricing` to be an array in the JSON string but got `%s`", jsonObj.get("passenger_pricing").toString()));
          }

          // validate the optional field `passenger_pricing` (array)
          for (int i = 0; i < jsonArraypassengerPricing.size(); i++) {
            DgPassengerPricing.validateJsonElement(jsonArraypassengerPricing.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DgItinerarySlice.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DgItinerarySlice' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DgItinerarySlice> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DgItinerarySlice.class));

       return (TypeAdapter<T>) new TypeAdapter<DgItinerarySlice>() {
           @Override
           public void write(JsonWriter out, DgItinerarySlice value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DgItinerarySlice read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DgItinerarySlice given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DgItinerarySlice
   * @throws IOException if the JSON string is invalid with respect to DgItinerarySlice
   */
  public static DgItinerarySlice fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DgItinerarySlice.class);
  }

  /**
   * Convert an instance of DgItinerarySlice to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

