/*
 * Airline API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hopper.cloud.airlines.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hopper.cloud.airlines.model.FormOfPayment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hopper.cloud.airlines.JSON;

/**
 * Request object related to the update of forms of payment for CFAR contract
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class UpdateCfarFormOfPaymentRequest {
  public static final String SERIALIZED_NAME_FORMS_OF_PAYMENT = "forms_of_payment";
  @SerializedName(SERIALIZED_NAME_FORMS_OF_PAYMENT)
    private List<FormOfPayment> formsOfPayment = new ArrayList<>();

  public UpdateCfarFormOfPaymentRequest() {
  }

  public UpdateCfarFormOfPaymentRequest formsOfPayment(List<FormOfPayment> formsOfPayment) {
    this.formsOfPayment = formsOfPayment;
    return this;
  }

  public UpdateCfarFormOfPaymentRequest addFormsOfPaymentItem(FormOfPayment formsOfPaymentItem) {
    if (this.formsOfPayment == null) {
      this.formsOfPayment = new ArrayList<>();
    }
    this.formsOfPayment.add(formsOfPaymentItem);
    return this;
  }

  /**
   * List of the forms of payment used to purchase the booking
   * @return formsOfPayment
   */
    public List<FormOfPayment> getFormsOfPayment() {
    return formsOfPayment;
  }

  public void setFormsOfPayment(List<FormOfPayment> formsOfPayment) {
    this.formsOfPayment = formsOfPayment;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCfarFormOfPaymentRequest updateCfarFormOfPaymentRequest = (UpdateCfarFormOfPaymentRequest) o;
    return Objects.equals(this.formsOfPayment, updateCfarFormOfPaymentRequest.formsOfPayment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formsOfPayment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCfarFormOfPaymentRequest {\n");
    sb.append("    formsOfPayment: ").append(toIndentedString(formsOfPayment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("forms_of_payment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("forms_of_payment");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateCfarFormOfPaymentRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateCfarFormOfPaymentRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateCfarFormOfPaymentRequest is not found in the empty JSON string", UpdateCfarFormOfPaymentRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateCfarFormOfPaymentRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateCfarFormOfPaymentRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateCfarFormOfPaymentRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("forms_of_payment").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `forms_of_payment` to be an array in the JSON string but got `%s`", jsonObj.get("forms_of_payment").toString()));
      }

      JsonArray jsonArrayformsOfPayment = jsonObj.getAsJsonArray("forms_of_payment");
      // validate the required field `forms_of_payment` (array)
      for (int i = 0; i < jsonArrayformsOfPayment.size(); i++) {
        FormOfPayment.validateJsonElement(jsonArrayformsOfPayment.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateCfarFormOfPaymentRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateCfarFormOfPaymentRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateCfarFormOfPaymentRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateCfarFormOfPaymentRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateCfarFormOfPaymentRequest>() {
           @Override
           public void write(JsonWriter out, UpdateCfarFormOfPaymentRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateCfarFormOfPaymentRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateCfarFormOfPaymentRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateCfarFormOfPaymentRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateCfarFormOfPaymentRequest
   */
  public static UpdateCfarFormOfPaymentRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateCfarFormOfPaymentRequest.class);
  }

  /**
   * Convert an instance of UpdateCfarFormOfPaymentRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

