name: increment-major
on:
  workflow_dispatch:
jobs:
  incrementMajor:
    name: incrementMajor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: increment Major Number
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementMajorVersion

      - id: get_version
        name: Retrieve version
        run: echo "::set-output name=VERSION::$(./gradlew printVersionName | grep version | cut -f 2 -d =)"

      - name: Commit and push the new version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git commit -a -m "[githubAction] increment Major Version to ${{ steps.get_version.outputs.VERSION }}"
          git push